name: app-ci
on:
  push:
    branches: ["main"]
    paths:
      - "src/**"
      - "requirements.txt"
      - "Dockerfile"
      - ".github/workflows/ci.yml"

permissions:
  contents: read
  packages: write

env:
  IMAGE: ${{ github.repository_owner }}/hello-app
  TAG: sha-${{ github.sha }}

jobs:
  build-scan-push:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      # Enable binfmt (qemu) for cross-arch builds
      - name: Enable binfmt (qemu)
        run: sudo podman run --rm --privileged docker.io/tonistiigi/binfmt --install all

      # Login to GHCR using Podman for build pulls
      - name: Login (Podman) to GHCR for build pulls
        uses: redhat-actions/podman-login@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build with Buildah multi-arch
      - name: Build (Buildah multi-arch)
        id: build
        uses: redhat-actions/buildah-build@v2
        with:
          image: ${{ env.IMAGE }}
          tags: latest ${{ env.TAG }}
          containerfiles: |
            ./Dockerfile
          platforms: linux/amd64,linux/arm64

      # Push with Podman using PAT
      - name: Push to GHCR (Podman) with PAT
        id: push
        uses: redhat-actions/push-to-registry@v2
        with:
          registry: ghcr.io
          image: ${{ steps.build.outputs.image }}
          tags: ${{ steps.build.outputs.tags }}
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GHCR_TOKEN }}

      # Print manifest digest for later use
      - name: Print manifest digest (latest)
        run: |
          ls -1 *_digest.txt || true
          echo "LATEST_MANIFEST_DIGEST=$(cat ghcr.io-${{ github.repository_owner }}-hello-app-latest_digest.txt || true)"

      # Scan the remote image in GHCR with authentication
      - name: Trivy scan (remote in GHCR by tag)
        uses: aquasecurity/trivy-action@0.33.1
        with:
          image-ref: ghcr.io/${{ env.IMAGE }}:${{ env.TAG }}
          format: 'table'
          vuln-type: 'os,library'
          scanners: 'vuln'
          severity: 'HIGH,CRITICAL'
          ignore-unfixed: false
          exit-code: '1'
        env:
          TRIVY_USERNAME: ${{ github.repository_owner }}
          TRIVY_PASSWORD: ${{ secrets.GHCR_TOKEN }}
